=== w3c/musicxml/schema/sounds.dtd
<!--
	MusicXML Sounds DTD

	Version 4.0
	
	Copyright Â© 2004-2021 the Contributors to the MusicXML 
	Specification, published by the W3C Music Notation Community
	Group under the W3C Community Final Specification Agreement 
	(FSA): 
	
	   https://www.w3.org/community/about/agreements/final/
	
	A human-readable summary is available:
	
	   https://www.w3.org/community/about/agreements/fsa-deed/

	The DTD version of the MusicXML format is deprecated as of
	Version 4.0. Use the sounds.xsd W3C XML Schema definition
	instead.
-->

<!--
	Starting with Version 3.0, the MusicXML format includes a
	standard set of instrument sounds to identify musical
	timbres. These values are used in the instrument-sound
	element.

	The standard sounds are listed in the sounds.xml file
	included with MusicXML 4.0. This is the document type
	definition for that file.

	Suggested use:
	
	<!DOCTYPE sounds PUBLIC
		"-//Recordare//DTD MusicXML 4.0 Sounds//EN"
		"http://www.musicxml.org/dtds/sounds.dtd">
	
	The XML catalog at catalog.xml supports validating against a
	local copy of this DTD rather than the networked version in
	the system ID. Software often has trouble using system IDs
	due to factors such as restrictions on network access, or
	resources having moved from the original specified location.
-->

<!-- Elements -->

<!--
	The sounds element is the document element for the
	sounds.xml file.
-->
<!ELEMENT sounds (sound+)>

<!--
	The sound element lists one of the standard sounds available
	in MusicXML 4.0. The required id attribute lists the MusicXML
	sound identifier string used by the instrument-sound element.

	The optional any, solo, and ensemble elements can be used for
	mapping MusicXML sound IDs to an application's or virtual
	instrument library's method of identifying sounds. These
	methods could include Sibelius SoundWorld IDs, capella
	genericsound IDs, and General MIDI patch numbers.

	The any element is used when a MusicXML ID refers to a single
	application or library sound ID, regardless of whether a
	solo or ensemble sound is used. The solo and ensemble elements
	are used when an application has different IDs for solo and
	ensemble sounds, as represented by the solo and ensemble
	elements in a MusicXML score file. The number attribute for
	the ensemble element represents the size of the ensemble,
	corresponding to the content of the ensemble element in a
	MusicXML score file.

	The primary attribute is used to distinguish a primary choice
	when multiple options are available in a single sounds.xml
	file. The primary attribute for the sound element is used when
	multiple sound elements map to the same application or library
	ID. In this case, the primary attribute indicates which of the
	MusicXML IDs is primary when mapping to a MusicXML sound id.

	Multiple any, solo, and ensemble elements can be used when
	multiple application sounds map to the same MusicXML sound id.
	The primary attribute indicates which of the any, solo, or
	ensemble elements is primary when mapping from a MusicXML
	sound id.
-->
<!ELEMENT sound (any* | (solo*, ensemble*))>
<!ATTLIST sound
    id ID #REQUIRED
    primary (yes | no) #IMPLIED
>
<!ELEMENT any (#PCDATA)>
<!ATTLIST any
    primary (yes | no) #IMPLIED
>
<!ELEMENT solo (#PCDATA)>
<!ATTLIST solo
    primary (yes | no) #IMPLIED
>
<!ELEMENT ensemble (#PCDATA)>
<!ATTLIST ensemble
    number NMTOKEN #IMPLIED
    primary (yes | no) #IMPLIED
>

=== w3c/musicxml/schema/sounds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sounds PUBLIC "-//Recordare//DTD MusicXML 4.0 Sounds//EN" "http://www.musicxml.org/dtds/sounds.dtd">

<!--
	MusicXML sounds file

	Version 4.0
	
	Copyright Â© 2004-2021 the Contributors to the MusicXML 
	Specification, published by the W3C Music Notation Community
	Group under the W3C Community Final Specification Agreement 
	(FSA): 
	
	   https://www.w3.org/community/about/agreements/final/
	
	A human-readable summary is available:
	
	   https://www.w3.org/community/about/agreements/fsa-deed/
-->

<!--
	Starting with Version 3.0, the MusicXML format includes a
	standard set of instrument sounds to identify musical
	timbres. These values are used in the instrument-sound
	element.

	This sounds.xml file contains the standard sounds that are
	included in MusicXML 4.0. The required id attribute
	lists the MusicXML sound identifier string used by
	the instrument-sound element.

	Applications may wish to provide a modified version of this
	file, where the element content includes an application's
	method for identifying sounds.
-->

<sounds>
   <sound id="brass.alphorn"/>
   <sound id="brass.alto-horn"/>
   <sound id="brass.baritone-horn"/>
   <sound id="brass.bugle"/>
   <sound id="brass.bugle.alto"/>
   <sound id="brass.bugle.baritone"/>
   <sound id="brass.bugle.contrabass"/>
   <sound id="brass.bugle.euphonium-bugle"/>
   <sound id="brass.bugle.mellophone-bugle"/>
   <sound id="brass.bugle.soprano"/>
   <sound id="brass.cimbasso"/>
   <sound id="brass.conch-shell"/>
   <sound id="brass.cornet"/>
   <sound id="brass.cornet.soprano"/>
   <sound id="brass.cornett"/>
   <sound id="brass.cornett.tenor"/>
   <sound id="brass.cornettino"/>
   <sound id="brass.didgeridoo"/>
   <sound id="brass.euphonium"/>
   <sound id="brass.fiscorn"/>
   <sound id="brass.flugelhorn"/>
   <sound id="brass.french-horn"/>
   <sound id="brass.group"/>
   <sound id="brass.group.synth"/>
   <sound id="brass.helicon"/>
   <sound id="brass.horagai"/>
   <sound id="brass.kuhlohorn"/>
   <sound id="brass.mellophone"/>
   <sound id="brass.natural-horn"/>
   <sound id="brass.ophicleide"/>
   <sound id="brass.posthorn"/>
   <sound id="brass.rag-dung"/>
   <sound id="brass.sackbutt"/>
   <sound id="brass.sackbutt.alto"/>
   <sound id="brass.sackbutt.bass"/>
   <sound id="brass.sackbutt.tenor"/>
   <sound id="brass.saxhorn"/>
   <sound id="brass.serpent"/>
   <sound id="brass.shofar"/>
   <sound id="brass.sousaphone"/>
   <sound id="brass.trombone"/>
   <sound id="brass.trombone.alto"/>
   <sound id="brass.trombone.bass"/>
   <sound id="brass.trombone.contrabass"/>
   <sound id="brass.trombone.tenor"/>
   <sound id="brass.trumpet"/>
   <sound id="brass.trumpet.baroque"/>
   <sound id="brass.trumpet.bass"/>
   <sound id="brass.trumpet.bflat"/>
   <sound id="brass.trumpet.c"/>
   <sound id="brass.trumpet.d"/>
   <sound id="brass.trumpet.piccolo"/>
   <sound id="brass.trumpet.pocket"/>
   <sound id="brass.trumpet.slide"/>
   <sound id="brass.trumpet.tenor"/>
   <sound id="brass.tuba"/>
   <sound id="brass.tuba.bass"/>
   <sound id="brass.tuba.subcontrabass"/>
   <sound id="brass.vienna-horn"/>
   <sound id="brass.vuvuzela"/>
   <sound id="brass.wagner-tuba"/>
   <sound id="drum.apentemma"/>
   <sound id="drum.ashiko"/>
   <sound id="drum.atabaque"/>
   <sound id="drum.atoke"/>
   <sound id="drum.atsimevu"/>
   <sound id="drum.axatse"/>
   <sound id="drum.bass-drum"/>
   <sound id="drum.bata"/>
   <sound id="drum.bata.itotele"/>
   <sound id="drum.bata.iya"/>
   <sound id="drum.bata.okonkolo"/>
   <sound id="drum.bendir"/>
   <sound id="drum.bodhran"/>
   <sound id="drum.bombo"/>
   <sound id="drum.bongo"/>
   <sound id="drum.bougarabou"/>
   <sound id="drum.buffalo-drum"/>
   <sound id="drum.cajon"/>
   <sound id="drum.chenda"/>
   <sound id="drum.chu-daiko"/>
   <sound id="drum.conga"/>
   <sound id="drum.cuica"/>
   <sound id="drum.dabakan"/>
   <sound id="drum.daff"/>
   <sound id="drum.dafli"/>
   <sound id="drum.daibyosi"/>
   <sound id="drum.damroo"/>
   <sound id="drum.darabuka"/>
   <sound id="drum.def"/>
   <sound id="drum.dhol"/>
   <sound id="drum.dholak"/>
   <sound id="drum.djembe"/>
   <sound id="drum.doira"/>
   <sound id="drum.dondo"/>
   <sound id="drum.doun-doun-ba"/>
   <sound id="drum.duff"/>
   <sound id="drum.dumbek"/>
   <sound id="drum.fontomfrom"/>
   <sound id="drum.frame-drum"/>
   <sound id="drum.frame-drum.arabian"/>
   <sound id="drum.geduk"/>
   <sound id="drum.ghatam"/>
   <sound id="drum.gome"/>
   <sound id="drum.group"/>
   <sound id="drum.group.chinese"/>
   <sound id="drum.group.ewe"/>
   <sound id="drum.group.indian"/>
   <sound id="drum.group.set"/>
   <sound id="drum.hand-drum"/>
   <sound id="drum.hira-daiko"/>
   <sound id="drum.ibo"/>
   <sound id="drum.igihumurizo"/>
   <sound id="drum.inyahura"/>
   <sound id="drum.ishakwe"/>
   <sound id="drum.jang-gu"/>
   <sound id="drum.kagan"/>
   <sound id="drum.kakko"/>
   <sound id="drum.kanjira"/>
   <sound id="drum.kendhang"/>
   <sound id="drum.kendhang.ageng"/>
   <sound id="drum.kendhang.ciblon"/>
   <sound id="drum.kenkeni"/>
   <sound id="drum.khol"/>
   <sound id="drum.kick-drum"/>
   <sound id="drum.kidi"/>
   <sound id="drum.ko-daiko"/>
   <sound id="drum.kpanlogo"/>
   <sound id="drum.kudum"/>
   <sound id="drum.lambeg"/>
   <sound id="drum.lion-drum"/>
   <sound id="drum.log-drum"/>
   <sound id="drum.log-drum.african"/>
   <sound id="drum.log-drum.native"/>
   <sound id="drum.log-drum.nigerian"/>
   <sound id="drum.madal"/>
   <sound id="drum.maddale"/>
   <sound id="drum.mridangam"/>
   <sound id="drum.naal"/>
   <sound id="drum.nagado-daiko"/>
   <sound id="drum.nagara"/>
   <sound id="drum.naqara"/>
   <sound id="drum.o-daiko"/>
   <sound id="drum.okawa"/>
   <sound id="drum.okedo-daiko"/>
   <sound id="drum.pahu-hula"/>
   <sound id="drum.pakhawaj"/>
   <sound id="drum.pandeiro"/>
   <sound id="drum.pandero"/>
   <sound id="drum.powwow"/>
   <sound id="drum.pueblo"/>
   <sound id="drum.repinique"/>
   <sound id="drum.riq"/>
   <sound id="drum.rototom"/>
   <sound id="drum.sabar"/>
   <sound id="drum.sakara"/>
   <sound id="drum.sampho"/>
   <sound id="drum.sangban"/>
   <sound id="drum.shime-daiko"/>
   <sound id="drum.slit-drum"/>
   <sound id="drum.slit-drum.krin"/>
   <sound id="drum.snare-drum"/>
   <sound id="drum.snare-drum.electric"/>
   <sound id="drum.sogo"/>
   <sound id="drum.surdo"/>
   <sound id="drum.tabla"/>
   <sound id="drum.tabla.bayan"/>
   <sound id="drum.tabla.dayan"/>
   <sound id="drum.tabor"/>
   <sound id="drum.taiko"/>
   <sound id="drum.talking"/>
   <sound id="drum.tama"/>
   <sound id="drum.tamborim"/>
   <sound id="drum.tamborita"/>
   <sound id="drum.tambourine"/>
   <sound id="drum.tamte"/>
   <sound id="drum.tangku"/>
   <sound id="drum.tan-tan"/>
   <sound id="drum.taphon"/>
   <sound id="drum.tar"/>
   <sound id="drum.tasha"/>
   <sound id="drum.tenor-drum"/>
   <sound id="drum.teponaxtli"/>
   <sound id="drum.thavil"/>
   <sound id="drum.the-box"/>
   <sound id="drum.timbale"/>
   <sound id="drum.timpani"/>
   <sound id="drum.tinaja"/>
   <sound id="drum.toere"/>
   <sound id="drum.tombak"/>
   <sound id="drum.tom-tom"/>
   <sound id="drum.tom-tom.synth"/>
   <sound id="drum.tsuzumi"/>
   <sound id="drum.tumbak"/>
   <sound id="drum.uchiwa-daiko"/>
   <sound id="drum.udaku"/>
   <sound id="drum.udu"/>
   <sound id="drum.zarb"/>
   <sound id="effect.aeolian-harp"/>
   <sound id="effect.air-horn"/>
   <sound id="effect.applause"/>
   <sound id="effect.bass-string-slap"/>
   <sound id="effect.bird"/>
   <sound id="effect.bird.nightingale"/>
   <sound id="effect.bird.tweet"/>
   <sound id="effect.breath"/>
   <sound id="effect.bubble"/>
   <sound id="effect.bullroarer"/>
   <sound id="effect.burst"/>
   <sound id="effect.car"/>
   <sound id="effect.car.crash"/>
   <sound id="effect.car.engine"/>
   <sound id="effect.car.pass"/>
   <sound id="effect.car.stop"/>
   <sound id="effect.crickets"/>
   <sound id="effect.dog"/>
   <sound id="effect.door.creak"/>
   <sound id="effect.door.slam"/>
   <sound id="effect.explosion"/>
   <sound id="effect.flute-key-click"/>
   <sound id="effect.footsteps"/>
   <sound id="effect.frogs"/>
   <sound id="effect.guitar-cutting"/>
   <sound id="effect.guitar-fret"/>
   <sound id="effect.gunshot"/>
   <sound id="effect.hand-clap"/>
   <sound id="effect.heartbeat"/>
   <sound id="effect.helicopter"/>
   <sound id="effect.high-q"/>
   <sound id="effect.horse-gallop"/>
   <sound id="effect.jet-plane"/>
   <sound id="effect.laser-gun"/>
   <sound id="effect.laugh"/>
   <sound id="effect.lions-roar"/>
   <sound id="effect.machine-gun"/>
   <sound id="effect.marching-machine"/>
   <sound id="effect.metronome-bell"/>
   <sound id="effect.metronome-click"/>
   <sound id="effect.pat"/>
   <sound id="effect.punch"/>
   <sound id="effect.rain"/>
   <sound id="effect.scratch"/>
   <sound id="effect.scream"/>
   <sound id="effect.seashore"/>
   <sound id="effect.siren"/>
   <sound id="effect.slap"/>
   <sound id="effect.snap"/>
   <sound id="effect.stamp"/>
   <sound id="effect.starship"/>
   <sound id="effect.stream"/>
   <sound id="effect.telephone-ring"/>
   <sound id="effect.thunder"/>
   <sound id="effect.train"/>
   <sound id="effect.trash-can"/>
   <sound id="effect.whip"/>
   <sound id="effect.whistle"/>
   <sound id="effect.whistle.mouth-siren"/>
   <sound id="effect.whistle.police"/>
   <sound id="effect.whistle.slide"/>
   <sound id="effect.whistle.train"/>
   <sound id="effect.wind"/>
   <sound id="keyboard.accordion"/>
   <sound id="keyboard.bandoneon"/>
   <sound id="keyboard.celesta"/>
   <sound id="keyboard.clavichord"/>
